#ifndef OPCODES_H
#define OPCODES_H

typedef enum opcode_kind_t {
	OPC_BIPUSH        = 0x10,
	OPC_ALOAD         = 0x19,
	OPC_ALOAD_0       = 0x2A,
	OPC_ALOAD_1       = 0x2B,
	OPC_ALOAD_2       = 0x2C,
	OPC_ALOAD_3       = 0x2D,
	OPC_GETSTATIC     = 0xB2,
	OPC_GETFIELD      = 0xB4,
	OPC_INVOKEVIRTUAL = 0xB6,
	OPC_INVOKESTATIC  = 0xB8,
	OPC_ILOAD_0       = 0x1A,
	OPC_ILOAD_1       = 0x1B,
	OPC_ILOAD_2       = 0x1C,
	OPC_ILOAD_3       = 0x1D,
	OPC_ILOAD         = 0x15,
	OPC_GOTO          = 0xA7,
	OPC_ICMPEQ        = 0x9F,
	OPC_ICMPNE        = 0xA0,
	OPC_ICMPLT        = 0xA1,
	OPC_ICMPGE        = 0xA2,
	OPC_ICMPGT        = 0xA3,
	OPC_ICMPLE        = 0xA4,
	OPC_IFEQ          = 0x99,
	OPC_IFNE          = 0x9A,
	OPC_IFLT          = 0x9B,
	OPC_IFGE          = 0x9C,
	OPC_IFGT          = 0x9D,
	OPC_IFLE          = 0x9E,
	OPC_ACMPEQ        = 0xA5,
	OPC_ACMPNE        = 0xA6,
	OPC_IFNONNULL     = 0xC7,
	OPC_IFNULL        = 0xC6,
	OPC_ISTORE_0      = 0x3B,
	OPC_ISTORE_1      = 0x3C,
	OPC_ISTORE_2      = 0x3D,
	OPC_ISTORE_3      = 0x3E,
	OPC_ISTORE        = 0x36,
	OPC_RETURN        = 0xB1,
	OPC_IRETURN       = 0xAC,
	OPC_ICONST_M1     = 0x2,
	OPC_ICONST_0      = 0x3,
	OPC_ICONST_1      = 0x4,
	OPC_ICONST_2      = 0x5,
	OPC_ICONST_3      = 0x6,
	OPC_ICONST_4      = 0x7,
	OPC_ICONST_5      = 0x8,
	OPC_IADD          = 0x60,
	OPC_ISUB          = 0x64,
	OPC_INVOKESPECIAL = 0xB7
} opcode_kind_t;

#endif
